### ISSUE TITLE
Sort output alphabetically

### ISSUE THREAD

**Issue by thiagonache** [bitfield/gotestdox#6]
Hi there,

I'd like to see the output of gotestdox ordered alphabetically without losing the beautiful colors in the output. Could you make it default via code so I can stop using `| sort`, please?
If you don't want to have to buffer the output to make sort possible by default, an argument would be good enough.

**Comment by bitfield** [comment]
(If we sort results per-package, we can also be more intelligent about grouping those results by package.)
